audio_encoder:
  # Optional: mld_clip, mld_bert
  target: convofusion.models.architectures.audioenc.AudioConvEncoder
  params:
    input_size: 80
    hidden_size: 256
    latent_dim: 512
    max_seq_len: ${DATASET.SAMPLER.MAX_LEN}
    fps: ${DATASET.BEATDND.FPS}
    sample_rate: ${DATASET.BEATDND.SR}
    hop_length: ${DATASET.BEATDND.HOP_LEN}
