motion_vae:
  # Optional: mld_vae, vposert_vae
  target: convofusion.models.architectures.vae.ConvoFusionVae
  params:
    arch: 'encoder_decoder'
    ff_size: 1024
    num_layers: 5
    num_heads: 2
    dropout: 0.1
    normalize_before: True
    activation: 'gelu'
    position_embedding: 'sine'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NFEATS}
    ablation: ${TRAIN.ABLATION}
    laplace_kernel_size: 5
