text_encoder:
  # Optional: mld_clip, mld_bert
  target: convofusion.models.architectures.t5.T5TextEncoder
  params:
    finetune: false # if false, model weights are frozen
    last_hidden_state: false # if true, the last hidden state is used as the text embedding
    latent_dim: 512
    modelpath: ${model.t5_path}
